### ISSUE TITLE
Support armv7l architecture

### ISSUE THREAD

**Issue by WaveHack** [JoshKeegan/docker-zip#23]
Would it be possible for you to include support for armv7l (linux/arm/v7) architecture please? I'd like to use the Docker Hub image on my Raspberry Pi.

Currently it's linux/amd64 only.

**Comment by JoshKeegan** [comment]
Hi,
Yes this can certainly become multi-arch 👍
 
If you need it urgently a PR is welcome & there's an example in another hobby project of mine here: https://github.com/JoshKeegan/sensors/blob/master/Makefile
If not, I'll pick this up when I get a moment, just not today :)

**Comment by WaveHack** [comment]
Thank you! No rush.

**Comment by JoshKeegan** [comment]
Added, let me know whether it's working for you.
